### PR TITLE
fix: update to latest version of urllib3

### PR DESCRIPTION
**Pull request by vinitkumar**
Loosen deps #157

### CODE REVIEW

**Comment by fmigneault** [comment]
Hi. Is it possible to have the tag released on PyPI?

**Comment by vinitkumar** [comment]
Yeah, sorry! It seems like it failed. I was under the impression that it already got released due to automation.

**Comment by vinitkumar** [comment]
@fmigneault And it is released. https://pypi.org/project/json2xml/

**Comment by fmigneault** [comment]
Thanks!

**Pull request merged**
