### PR TITLE
improvements on dicttoxml

### PR DESCRIPTION
**Pull request by DirkRichter**
-  support of namespaces
-  moving full object serialization into loglevel debug (reduce cpu + out of mem on large objects)
-  more control parameters on xml generation: allow custom xml attributes via attr + optionally omit encapsulating xml-nodes via Flat

Sorry, I was not able to extend your pull-request #120, thus i ceated a new one with fix for the failing test.

### CODE REVIEW

**Comment by Flat** [comment]
Can you please stop mentioning me? Thank you.

**Comment by vinitkumar** [comment]
> Can you please stop mentioning me? Thank you.
@Flat I think it was a honest mistake from the contributor and not intentional. I have edited the description and it should be fine now. Apologies on the unintentional spam.

**Comment by vinitkumar** [comment]
> Can you please stop mentioning me? Thank you.
@Flat I think it was a honest mistake from the contributor and not intentional. I have edited the description and it should be fine now. Apologies on the unintentional spam.

**Comment by vinitkumar** [comment]
@DirkRichter Thanks for the timely fix. Since it's a big change, let me look into the code and understand before merging it.

**Comment by vinitkumar** [comment]
@DirkRichter Looked into the the code, it mostly looks good. Can we also adds tests supporting this new functionality. Something similar to how I test these? https://github.com/vinitkumar/json2xml/blob/master/tests/test_json2xml.py#L189 using an example json file: https://github.com/vinitkumar/json2xml/blob/master/examples/booleanjson2.json

And while we are at it, we should also update the readme about this newly added support for namespaces. 

Please let me know what you think about these?

**Comment by DirkRichter** [comment]
Your new test shows problems with the old dicttoxml. The json sample

```
{
      "boolean_list": [true, false],
      "number_array": [1, 2, 3],
      "string_array": ["a", "b", "c"]
}
```
results in this xml:
```
<all>
        <item type="bool">true</item>
        <item type="bool">false</item>
        <item type="int">1</item>
        <item type="int">2</item>
        <item type="int">3</item>
        <string_array type="list">
                <item type="str">a</item>
                <item type="str">b</item>
                <item type="str">c</item>
        </string_array>
</all>
```
in my fixed dicttoxml version, corrently this xml is produced:
```
<all>
        <boolean_list type="list">
                <item type="bool">true</item>
                <item type="bool">false</item>
        </boolean_list>
        <number_array type="list">
                <item type="int">1</item>
                <item type="int">2</item>
                <item type="int">3</item>
        </number_array>
        <string_array type="list">
                <item type="str">a</item>
                <item type="str">b</item>
                <item type="str">c</item>
        </string_array>
</all>
```
Thus i will adapt the test. Or is there something, i'm not seeing?

**Comment by vinitkumar** [comment]
> Your new test shows problems with the old dicttoxml. The json sample
> 
> ```
> {
>       "boolean_list": [true, false],
>       "number_array": [1, 2, 3],
>       "string_array": ["a", "b", "c"]
> }
> ```
> 
> results in this xml:
> 
> ```
> <all>
>         <item type="bool">true</item>
>         <item type="bool">false</item>
>         <item type="int">1</item>
>         <item type="int">2</item>
>         <item type="int">3</item>
>         <string_array type="list">
>                 <item type="str">a</item>
>                 <item type="str">b</item>
>                 <item type="str">c</item>
>         </string_array>
> </all>
> ```
> 
> in my fixed dicttoxml version, corrently this xml is produced:
> 
> ```
> <all>
>         <boolean_list type="list">
>                 <item type="bool">true</item>
>                 <item type="bool">false</item>
>         </boolean_list>
>         <number_array type="list">
>                 <item type="int">1</item>
>                 <item type="int">2</item>
>                 <item type="int">3</item>
>         </number_array>
>         <string_array type="list">
>                 <item type="str">a</item>
>                 <item type="str">b</item>
>                 <item type="str">c</item>
>         </string_array>
> </all>
> ```
> 
> Thus i will adapt the test. Or is there something, i'm not seeing?

I think your changes are correct. Please adapt the test accordingly.

**Comment by vinitkumar** [comment]
@DirkRichter There seems to be some conflicts as well. Can you please resolve them too?

**Comment by DirkRichter** [comment]
- again merged with master 
- conflicts solved
- i think you can also drop dependency to regular xmltodict in \.github\workflows\pythonpackage.yml
` pip install xmltodict==0.12.0`

**Comment by vinitkumar** [comment]
> i think you can also drop dependency to regular xmltodict in .github\workflows\pythonpackage.yml
pip install xmltodict==0.12.0

@DirkRichter Please feel free to make the changes.

**Comment by vinitkumar** [comment]
@DirkRichter Also, I added flake8 and isort in the mix, so if there are lint failures, CI will fail and you will need to clean up the code.

**Comment by vinitkumar** [comment]
@DirkRichter Thanks a tonne for all your hardwork. I will merge the PR now and then I want the code to brew for a while, and then make a major release. I might also do some optimisation on top of it before making the release.

**Comment by vinitkumar** [comment]
@DirkRichter I think some code went missing.

```
<all>
        <boolean_list type="list">
                <item type="bool">true</item>
                <item type="bool">false</item>
        </boolean_list>
        <number_array type="list">
                <item type="int">1</item>
                <item type="int">2</item>
                <item type="int">3</item>
        </number_array>
        <string_array type="list">
                <item type="str">a</item>
                <item type="str">b</item>
                <item type="str">c</item>
        </string_array>
</all>
```

This doesn't seems to work with that I merged last evening.

**Pull request merged**
