### PR TITLE
item_wrap for str and int

### LINKED ISSUE #93: item_wrap for str and int
`item_wrap=False` currently only supports list of dict

It should also support list of `str` and `int`

Input:
```json
{"my_str_items":["a","b"]}
```

item_wrap=False output:
```xml
<all>
  <my_str_items type="list">
    <item type="str">a</item>
    <item type="str">b</item>
  </my_str_items>
</all>
```

item_wrap=True output:
```xml
<all>
  <my_str_items>a</my_str_items>
  <my_str_items>b</my_str_items>
</all>
```

### PR DESCRIPTION
**Pull request by jgroom33**
resolve #93

### CODE REVIEW

**Comment by vinitkumar** [comment]
Thanks for your contribution, and apologies for a bit of late response, I have been swamped at work.

I will review the code and if all goes fine, I will merge it.

**Comment by vinitkumar** [comment]
@jgroom33 Can you please also update the readme with an example of the above change, this might help people who are looking for similar functionality with this library.

**Comment by jgroom33** [comment]
I refactored a bit and added a couple new tests too

**Comment by vinitkumar** [comment]
> I refactored a bit and added a couple new tests too

Thanks, this looks great. I had a question though, it this email correct? `<mail@jgroom33@outlook.com>` It contains 2 `@` in it. If not, please update it and this looks good to be merged.

**Comment by jgroom33** [comment]
> 

fixed

**Comment by vinitkumar** [comment]
Awesome. Thank you :) I will be merging it now and hopefully release a new build to PYPI as well.

**Comment by vinitkumar** [comment]
@jgroom33 It is now released on the PyPI: https://pypi.org/project/json2xml/3.9.0/

Congrats on your first contributions and release for PYPI.

I hope you contribute more to this project 🥂

**Pull request merged**
