### PR TITLE
Attr test

### PR DESCRIPTION
**Pull request by Jeroendevr**
For the dicttoxml module did not have a direct test where `attr_type=True` it was only indirectly tested using json2xml. So hereby a small increase of tests. 

Forgot to branch properly so hereby also my solution to #165 
Although I have some Ideas to make the code cleaner and perhaps another test or two I would like your opinon.

### CODE REVIEW

**Comment by vinitkumar** [comment]
This looks good. This fix is in line with the discussion we had in the twitter thread, right?

**Comment by Jeroendevr** [comment]
I don't have twitter, I think you meant PR #165 or issue #163? That's correct! this is THE FIX 😀

**Comment by vinitkumar** [comment]
> I don't have twitter, I think you meant PR #165 or issue #163? That's correct! this is THE FIX 😀

I am sorry I did a typo. I meant the GitHub issue thread. Furthermore, I will review the code a bit deeply and if all is good, will merge and cut a release.

**Comment by Jeroendevr** [comment]
Yes that's great. I'll await your feedback and do some refactoring afterwards.

**Review by vinitkumar — APPROVED** [review]

**Review by vinitkumar — APPROVED** [review]

**Pull request merged**
